// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYTHdbV4bi76fs8xVNxKXHjYFPxsTe2Nc',
    appId: '1:628767787869:web:4a345a7878e5a7d57336b4',
    messagingSenderId: '628767787869',
    projectId: 'wassit-khier',
    authDomain: 'wassit-khier.firebaseapp.com',
    storageBucket: 'wassit-khier.firebasestorage.app',
    measurementId: 'G-J4EV9VHK6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgnIXhGwe9v9W48xnJmxiue1r9I667aIg',
    appId: '1:628767787869:android:4431fe26d6dc68677336b4',
    messagingSenderId: '628767787869',
    projectId: 'wassit-khier',
    storageBucket: 'wassit-khier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWurugGIBLc9xdZMmmYqro7VFt-21tLY8',
    appId: '1:628767787869:ios:895c278149a2bd557336b4',
    messagingSenderId: '628767787869',
    projectId: 'wassit-khier',
    storageBucket: 'wassit-khier.firebasestorage.app',
    androidClientId: '628767787869-2eh98m8pvm6eouop6olaumlitjrut595.apps.googleusercontent.com',
    iosClientId: '628767787869-g5bli6ookr8gilc1kb92km31m25p7h0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasitKheir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWurugGIBLc9xdZMmmYqro7VFt-21tLY8',
    appId: '1:628767787869:ios:895c278149a2bd557336b4',
    messagingSenderId: '628767787869',
    projectId: 'wassit-khier',
    storageBucket: 'wassit-khier.firebasestorage.app',
    androidClientId: '628767787869-2eh98m8pvm6eouop6olaumlitjrut595.apps.googleusercontent.com',
    iosClientId: '628767787869-g5bli6ookr8gilc1kb92km31m25p7h0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasitKheir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYTHdbV4bi76fs8xVNxKXHjYFPxsTe2Nc',
    appId: '1:628767787869:web:04864b485fa404e37336b4',
    messagingSenderId: '628767787869',
    projectId: 'wassit-khier',
    authDomain: 'wassit-khier.firebaseapp.com',
    storageBucket: 'wassit-khier.firebasestorage.app',
    measurementId: 'G-622EKZ980X',
  );

}
